export const cityMap = {
  "基隆市": "Keelung",
  "臺北市": "Taipei",
  "新北市": "New Taipei",
  "桃園市": "Taoyuan",
  "新竹市": "Hsinchu",
  "新竹縣": "Hsinchu County",
  "苗栗縣": "Miaoli",
  "臺中市": "Taichung",
  "彰化縣": "Changhua",
  "南投縣": "Nantou",
  "雲林縣": "Yunlin",
  "嘉義市": "Chiayi",
  "嘉義縣": "Chiayi County",
  "臺南市": "Tainan",
  "高雄市": "Kaohsiung",
  "屏東縣": "Pingtung",
  "宜蘭縣": "Yilan",
  "花蓮縣": "Hualien",
  "臺東縣": "Taitung",
  "澎湖縣": "Penghu",
  "金門縣": "Kinmen",
  "連江縣": "Matsu"
};
